WITH RECURSIVE CTE AS(
    SELECT ID,1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT B.ID AS ID ,CTE.GENERATION+1 AS GENERATION
    FROM CTE 
    JOIN
    ECOLI_DATA AS B
    ON CTE.ID=B.PARENT_ID
)

SELECT 
        COUNT(ID) AS COUNT,GENERATION
FROM CTE
WHERE ID NOT IN(SELECT PARENT_ID FROM ECOLI_DATA WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION
ORDER BY GENERATION