WITH AB AS(
SELECT B.HISTORY_ID,A.DAILY_FEE,DATEDIFF(B.END_DATE,B.START_DATE)+1 AS PERIOD
FROM CAR_RENTAL_COMPANY_CAR AS A,CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B
WHERE A.CAR_ID=B.CAR_ID AND A.CAR_TYPE='트럭')


SELECT A.HISTORY_ID,IF(B.DURATION_TYPE IS NOT NULL,ROUND(A.FEE*(100-B.DISCOUNT_RATE)*0.01),ROUND(A.FEE)) AS FEE
FROM
(SELECT HISTORY_ID,DAILY_FEE*PERIOD AS FEE, IF(PERIOD>=90,'90일 이상',IF(PERIOD>=30,'30일 이상',IF(PERIOD>=7,'7일 이상',NULL))) AS DURATION_TYPE FROM AB) AS A LEFT JOIN (SELECT * FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE='트럭') AS B
ON A.DURATION_TYPE=B.DURATION_TYPE 
ORDER BY FEE DESC,A.HISTORY_ID DESC
